version: '3'

services:
  test:
    build: .
    volumes:
      - .:/app
      - /app/node_modules
    command: npm test

  test-watch:
    build: .
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run test:watch

  test-coverage:
    build: .
    volumes:
      - .:/app
      - /app/node_modules
    command: npm test -- --coverage 